const fs = require("fs");
const crypto = require("crypto");
const path = require("path");

const HYMNS_PATH = "hymns.json";
const OCCURRENCES_PATH = "docs/TPMAC_HYMNS_2021-05-22_to_2026-05-22_OCCURRENCES.csv";
const OUTPUT_CSV_PATH = "docs/TPMAC_LYRIC_VERIFICATION_2026-05-22.csv";
const OUTPUT_REPORT_PATH = "docs/TPMAC_LYRIC_VERIFICATION_2026-05-22.md";
const CACHE_DIR = ".cache/tpmac-lyric-verify";

const LIMIT = Number(process.env.TPMAC_LYRIC_LIMIT || 0);
const CONCURRENCY = Number(process.env.TPMAC_LYRIC_CONCURRENCY || 8);
const MAX_OCCURRENCES_PER_HYMN = Number(process.env.TPMAC_LYRIC_MAX_OCCURRENCES || 3);
const YOUTUBE_CACHE_VERSION = 2;

const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125 Safari/537.36";

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function csvEscape(value) {
  const text = String(value ?? "");
  return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

function parseCsv(text) {
  const rows = [];
  let row = [];
  let value = "";
  let quoted = false;

  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    const next = text[index + 1];
    if (quoted) {
      if (char === '"' && next === '"') {
        value += '"';
        index += 1;
      } else if (char === '"') {
        quoted = false;
      } else {
        value += char;
      }
    } else if (char === '"') {
      quoted = true;
    } else if (char === ",") {
      row.push(value);
      value = "";
    } else if (char === "\n") {
      row.push(value.replace(/\r$/, ""));
      rows.push(row);
      row = [];
      value = "";
    } else {
      value += char;
    }
  }

  if (value || row.length) {
    row.push(value.replace(/\r$/, ""));
    rows.push(row);
  }
  return rows;
}

function parseOccurrences() {
  const rows = parseCsv(fs.readFileSync(OCCURRENCES_PATH, "utf8"));
  const headers = rows.shift();
  const indexes = Object.fromEntries(headers.map((header, index) => [header.replace(/^\uFEFF/, ""), index]));
  const byTitle = new Map();
  for (const row of rows) {
    const title = row[indexes.title];
    if (!title) continue;
    const item = {
      date: row[indexes.date],
      title,
      labelExcerpt: row[indexes.label_excerpt],
      sourceUrl: row[indexes.source_url],
    };
    if (!byTitle.has(title)) byTitle.set(title, []);
    byTitle.get(title).push(item);
  }
  return byTitle;
}

function hash(value) {
  return crypto.createHash("sha1").update(value).digest("hex");
}

function canonical(value) {
  return String(value || "")
    .normalize("NFKC")
    .replace(/[祢袮]/g, "你")
    .replace(/[臺台]/g, "台")
    .replace(/\s+/g, "");
}

function compareText(value) {
  return canonical(value)
    .replace(/副歌|尾句|過門|重唱|曲詞|詞曲|中譯|原曲|詩歌|獻詩|唱詩|回應詩|主日|崇拜/g, "")
    .replace(/[^\p{Letter}\p{Number}]/gu, "")
    .toLowerCase();
}

function visibleLength(value) {
  return compareText(value).length;
}

function decodeEntities(value) {
  return String(value || "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#x([0-9a-f]+);/gi, (_, hex) => String.fromCodePoint(Number.parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, number) => String.fromCodePoint(Number.parseInt(number, 10)));
}

function cleanDescription(value) {
  const lines = String(value || "")
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .filter((line) => !/^https?:\/\//i.test(line))
    .filter((line) => !/^#/.test(line))
    .filter((line) => !/^(provided to youtube by|released on:|auto-generated by youtube|composer:|lyricist:|arranger:|producer:|associated performer:|music publisher:)/i.test(line))
    .filter((line) => !/^℗/.test(line))
    .filter((line) => !/^©/.test(line));
  return lines.join("\n");
}

function looksLikeLyrics(value) {
  const cleaned = cleanDescription(value);
  const lineCount = cleaned.split(/\r?\n/).filter((line) => visibleLength(line) >= 4).length;
  const length = visibleLength(cleaned);
  const hasLyricMarkers = /副歌|chorus|verse|主歌|尾句|敬拜|讚美|耶穌|上帝|耶和華|祢|你/.test(cleaned);
  return length >= 90 && (lineCount >= 3 || hasLyricMarkers);
}

async function importPdfJs() {
  try {
    return await import("pdfjs-dist/legacy/build/pdf.mjs");
  } catch (error) {
    throw new Error(
      `Missing pdfjs-dist. Run: npm install --no-save --no-package-lock pdfjs-dist@4\n${error.message}`
    );
  }
}

async function fetchText(url) {
  const response = await fetch(url, {
    headers: {
      "Accept-Language": "zh-Hant,zh-HK;q=0.9,en;q=0.7",
      "User-Agent": USER_AGENT,
    },
    cache: "no-store",
  });
  if (!response.ok) throw new Error(`${response.status} ${response.statusText} ${url}`);
  return response.text();
}

async function fetchBuffer(url) {
  const response = await fetch(url, {
    headers: {
      "Accept-Language": "zh-Hant,zh-HK;q=0.9,en;q=0.7",
      "User-Agent": USER_AGENT,
    },
    cache: "no-store",
  });
  if (!response.ok) throw new Error(`${response.status} ${response.statusText} ${url}`);
  return new Uint8Array(await response.arrayBuffer());
}

async function getPdfText(url, pdfjs) {
  ensureDir(path.join(CACHE_DIR, "pdf-text"));
  const cachePath = path.join(CACHE_DIR, "pdf-text", `${hash(url)}.txt`);
  if (fs.existsSync(cachePath)) return fs.readFileSync(cachePath, "utf8");

  const data = await fetchBuffer(url);
  const doc = await pdfjs.getDocument({ data, disableWorker: true }).promise;
  const pages = [];
  for (let pageNumber = 1; pageNumber <= doc.numPages; pageNumber += 1) {
    const page = await doc.getPage(pageNumber);
    const content = await page.getTextContent();
    pages.push(`---PAGE ${pageNumber}--- ${content.items.map((item) => item.str).join(" ")}`);
  }
  const text = pages.join("\n");
  fs.writeFileSync(cachePath, text);
  return text;
}

function findAllIndexes(text, needle) {
  const indexes = [];
  let cursor = -1;
  while ((cursor = text.indexOf(needle, cursor + 1)) >= 0) indexes.push(cursor);
  return indexes;
}

function nextBoundary(text, from) {
  const boundaries = [
    "堂詩歌..《",
    "獻詩..《",
    "回應詩..《",
    "唱詩..《",
    "《",
    "【",
    "---PAGE",
  ]
    .map((marker) => text.indexOf(marker, from))
    .filter((index) => index >= 0);
  return boundaries.length ? Math.min(...boundaries) : -1;
}

function extractLyricCandidate(pdfText, title) {
  const text = canonical(pdfText);
  const titleKey = canonical(title);
  const positions = findAllIndexes(text, titleKey);
  const candidates = [];

  for (const position of positions) {
    const bodyStart = position + titleKey.length;
    let end = nextBoundary(text, bodyStart + 12);
    if (end < 0 || end <= bodyStart) end = Math.min(text.length, position + 2200);
    const segment = text.slice(position, Math.min(end, position + 2600));
    const segmentForCompare = compareText(segment);
    const hasLyricMarkers = /[1-9]\.|副歌|尾句|過門|阿們|哈利路亞/.test(segment);
    const dots = (segment.match(/\./g) || []).length;
    const score =
      Math.min(segmentForCompare.length, 900) +
      (hasLyricMarkers ? 250 : 0) -
      Math.min(dots * 4, 240);
    candidates.push({ segment, length: segmentForCompare.length, score });
  }

  candidates.sort((a, b) => b.score - a.score);
  return candidates[0] || null;
}

async function getTpmacLyrics(hymn, occurrences, pdfjs) {
  const checked = [];
  for (const occurrence of occurrences.slice(0, MAX_OCCURRENCES_PER_HYMN)) {
    try {
      const pdfText = await getPdfText(occurrence.sourceUrl, pdfjs);
      const candidate = extractLyricCandidate(pdfText, hymn.title);
      checked.push({
        occurrence,
        candidate,
        score: candidate?.score || 0,
      });
    } catch (error) {
      checked.push({ occurrence, error: error.message, score: 0 });
    }
  }
  checked.sort((a, b) => b.score - a.score);
  const best = checked[0];
  if (!best?.candidate || best.candidate.length < 80) {
    return {
      status: "no_tpmac_lyric_segment",
      sourceDate: best?.occurrence?.date || "",
      sourceUrl: best?.occurrence?.sourceUrl || "",
      text: "",
      textHash: "",
      chars: best?.candidate?.length || 0,
    };
  }
  const text = best.candidate.segment;
  return {
    status: "ok",
    sourceDate: best.occurrence.date,
    sourceUrl: best.occurrence.sourceUrl,
    text,
    textHash: hash(compareText(text)),
    chars: visibleLength(text),
  };
}

function extractPlayerResponse(html) {
  const marker = "ytInitialPlayerResponse";
  const markerIndex = html.indexOf(marker);
  if (markerIndex < 0) return null;
  let start = html.indexOf("{", markerIndex);
  if (start < 0) return null;
  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let index = start; index < html.length; index += 1) {
    const char = html[index];
    if (inString) {
      if (escaped) escaped = false;
      else if (char === "\\") escaped = true;
      else if (char === '"') inString = false;
      continue;
    }
    if (char === '"') inString = true;
    else if (char === "{") depth += 1;
    else if (char === "}") {
      depth -= 1;
      if (depth === 0) return JSON.parse(html.slice(start, index + 1));
    }
  }
  return null;
}

function chooseCaptionTrack(tracks = []) {
  const preferred = ["zh-Hant", "zh-TW", "zh-HK", "zh", "zh-Hans", "zh-CN", "en"];
  return [...tracks].sort((a, b) => {
    const ai = preferred.indexOf(a.languageCode);
    const bi = preferred.indexOf(b.languageCode);
    const as = ai >= 0 ? ai : 99;
    const bs = bi >= 0 ? bi : 99;
    const ak = a.kind === "asr" ? 1 : 0;
    const bk = b.kind === "asr" ? 1 : 0;
    return as - bs || ak - bk;
  })[0];
}

async function getYouTubeText(videoId) {
  ensureDir(path.join(CACHE_DIR, "youtube"));
  const cachePath = path.join(CACHE_DIR, "youtube", `${videoId}.json`);
  let cached = null;
  if (fs.existsSync(cachePath)) {
    cached = JSON.parse(fs.readFileSync(cachePath, "utf8"));
    if (cached.cacheVersion === YOUTUBE_CACHE_VERSION) return cached;
    const upgraded = upgradeCachedYouTubeText(cached);
    if (upgraded) {
      fs.writeFileSync(cachePath, JSON.stringify(upgraded, null, 2));
      return upgraded;
    }
  }

  let html = "";
  try {
    html = await fetchText(`https://www.youtube.com/watch?v=${videoId}&hl=zh-Hant&gl=HK`);
  } catch (error) {
    if (cached) {
      return {
        cacheVersion: YOUTUBE_CACHE_VERSION,
        title: cached.title || "",
        source: "error",
        chars: 0,
        text: "",
        textHash: "",
        error: error.message,
      };
    }
    throw error;
  }
  const player = extractPlayerResponse(html);
  if (!player) throw new Error(`Cannot parse YouTube player response for ${videoId}`);

  const title = player.videoDetails?.title || "";
  const description =
    player.videoDetails?.shortDescription ||
    player.microformat?.playerMicroformatRenderer?.description?.simpleText ||
    "";
  const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
  const track = chooseCaptionTrack(tracks);

  let source = "";
  let text = "";
  if (track?.baseUrl) {
    const captionXml = await fetchText(track.baseUrl);
    text = [...captionXml.matchAll(/<text\b[^>]*>([\s\S]*?)<\/text>/g)]
      .map((match) => decodeEntities(match[1]).replace(/\s+/g, " ").trim())
      .filter(Boolean)
      .join(" ");
    source = `caption:${track.languageCode}${track.kind === "asr" ? ":asr" : ""}`;
  }

  if (visibleLength(text) < 50 && looksLikeLyrics(description)) {
    text = cleanDescription(description);
    source = "description";
  }

  const result = {
    cacheVersion: YOUTUBE_CACHE_VERSION,
    title,
    source: source || "none",
    chars: visibleLength(text),
    text,
    textHash: text ? hash(compareText(text)) : "",
  };
  fs.writeFileSync(cachePath, JSON.stringify(result, null, 2));
  return result;
}

function upgradeCachedYouTubeText(cached) {
  if (!cached || typeof cached !== "object") return null;
  const title = cached.title || "";
  const source = cached.source || "none";
  const text = cached.text || "";

  if (source.startsWith("caption") && visibleLength(text) >= 50) {
    return {
      cacheVersion: YOUTUBE_CACHE_VERSION,
      title,
      source,
      chars: visibleLength(text),
      text,
      textHash: text ? hash(compareText(text)) : "",
    };
  }

  if (source === "description" && looksLikeLyrics(text)) {
    const cleaned = cleanDescription(text);
    return {
      cacheVersion: YOUTUBE_CACHE_VERSION,
      title,
      source: "description",
      chars: visibleLength(cleaned),
      text: cleaned,
      textHash: cleaned ? hash(compareText(cleaned)) : "",
    };
  }

  if (title || source !== "none") {
    return {
      cacheVersion: YOUTUBE_CACHE_VERSION,
      title,
      source: "none",
      chars: 0,
      text: "",
      textHash: "",
    };
  }

  return null;
}

function makeNgrams(text, size = 5) {
  const value = compareText(text);
  const grams = new Set();
  for (let index = 0; index <= value.length - size; index += 1) {
    grams.add(value.slice(index, index + size));
  }
  return grams;
}

function scoreLyrics(tpmacText, youtubeText) {
  const source = compareText(tpmacText);
  const target = compareText(youtubeText);
  if (source.length < 50 || target.length < 50) {
    return { anchorHits: 0, anchorTotal: 0, anchorRate: 0, commonRate: 0 };
  }

  const grams = makeNgrams(source, 5);
  let hits = 0;
  for (const gram of grams) {
    if (target.includes(gram)) hits += 1;
  }

  const sourceChars = new Set([...source]);
  let commonChars = 0;
  for (const char of sourceChars) {
    if (target.includes(char)) commonChars += 1;
  }

  return {
    anchorHits: hits,
    anchorTotal: grams.size,
    anchorRate: grams.size ? hits / grams.size : 0,
    commonRate: sourceChars.size ? commonChars / sourceChars.size : 0,
  };
}

function classify(tpmac, youtube, score) {
  if (tpmac.status !== "ok") return "no_tpmac_lyrics";
  if (!youtube.text || youtube.chars < 50) return "no_youtube_lyrics";
  if (score.anchorRate >= 0.2 || (score.anchorRate >= 0.12 && score.commonRate >= 0.72)) {
    return "lyrics_confirmed";
  }
  if (score.anchorRate >= 0.07 || (score.anchorRate >= 0.04 && score.commonRate >= 0.78)) {
    return "lyrics_weak_match";
  }
  if (youtube.chars >= 120 && score.anchorRate < 0.015 && score.commonRate < 0.62) {
    return "probable_mismatch";
  }
  return "needs_manual_review";
}

async function mapConcurrent(items, limit, mapper) {
  const output = new Array(items.length);
  let cursor = 0;
  async function worker() {
    while (cursor < items.length) {
      const index = cursor;
      cursor += 1;
      output[index] = await mapper(items[index], index);
    }
  }
  await Promise.all(Array.from({ length: limit }, () => worker()));
  return output;
}

async function main() {
  ensureDir(CACHE_DIR);
  const pdfjs = await importPdfJs();
  const hymns = JSON.parse(fs.readFileSync(HYMNS_PATH, "utf8"));
  const occurrencesByTitle = parseOccurrences();
  const selected = LIMIT > 0 ? hymns.slice(0, LIMIT) : hymns;

  console.log(`Verifying lyrics for ${selected.length} hymns...`);
  const results = await mapConcurrent(selected, CONCURRENCY, async (hymn, index) => {
    const occurrences = occurrencesByTitle.get(hymn.title) || [];
    const tpmac = await getTpmacLyrics(hymn, occurrences, pdfjs);
    let youtube = { source: "error", chars: 0, text: "", textHash: "", title: "", error: "" };
    try {
      youtube = await getYouTubeText(hymn.videoId);
    } catch (error) {
      youtube.error = error.message;
    }
    const score = scoreLyrics(tpmac.text, youtube.text);
    const status = classify(tpmac, youtube, score);
    if ((index + 1) % 25 === 0 || index === selected.length - 1) {
      console.log(`${index + 1}/${selected.length} ${hymn.number} ${status}`);
    }
    return {
      number: hymn.number,
      title: hymn.title,
      videoId: hymn.videoId,
      youtubeTitle: youtube.title,
      tpmacSourceDate: tpmac.sourceDate,
      tpmacSourceUrl: tpmac.sourceUrl,
      tpmacLyricChars: tpmac.chars,
      tpmacLyricHash: tpmac.textHash,
      youtubeTextSource: youtube.source,
      youtubeTextChars: youtube.chars,
      youtubeTextHash: youtube.textHash,
      anchorHits: score.anchorHits,
      anchorTotal: score.anchorTotal,
      anchorRate: Number(score.anchorRate.toFixed(4)),
      commonRate: Number(score.commonRate.toFixed(4)),
      status,
      note: youtube.error || "",
    };
  });

  const headers = [
    "number",
    "title",
    "video_id",
    "youtube_title",
    "tpmac_source_date",
    "tpmac_source_url",
    "tpmac_lyric_chars",
    "tpmac_lyric_hash",
    "youtube_text_source",
    "youtube_text_chars",
    "youtube_text_hash",
    "anchor_hits",
    "anchor_total",
    "anchor_rate",
    "common_rate",
    "status",
    "note",
  ];
  const csvRows = [
    headers,
    ...results.map((result) => [
      result.number,
      result.title,
      result.videoId,
      result.youtubeTitle,
      result.tpmacSourceDate,
      result.tpmacSourceUrl,
      result.tpmacLyricChars,
      result.tpmacLyricHash,
      result.youtubeTextSource,
      result.youtubeTextChars,
      result.youtubeTextHash,
      result.anchorHits,
      result.anchorTotal,
      result.anchorRate,
      result.commonRate,
      result.status,
      result.note,
    ]),
  ];
  fs.writeFileSync(OUTPUT_CSV_PATH, `${csvRows.map((row) => row.map(csvEscape).join(",")).join("\n")}\n`);

  const counts = results.reduce((map, result) => {
    map.set(result.status, (map.get(result.status) || 0) + 1);
    return map;
  }, new Map());
  const statusRows = [...counts.entries()].sort((a, b) => b[1] - a[1]);
  const reviewRows = results
    .filter((result) => ["probable_mismatch", "needs_manual_review", "lyrics_weak_match"].includes(result.status))
    .slice(0, 80);

  const report = [
    "# TPMAC Lyric Verification - 2026-05-22",
    "",
    "This report compares TPMAC bulletin lyric text with available YouTube captions or descriptions. Full lyrics are not stored in this repository; only counts, hashes, scores, and source references are saved.",
    "",
    "## Scope",
    "",
    `- Hymns checked: ${results.length}`,
    `- TPMAC lyric segments found: ${results.filter((row) => row.tpmacLyricChars >= 80).length}`,
    `- YouTube text sources found: ${results.filter((row) => row.youtubeTextChars >= 50).length}`,
    "",
    "## Status Counts",
    "",
    "| Status | Count |",
    "|---|---:|",
    ...statusRows.map(([status, count]) => `| ${status} | ${count} |`),
    "",
    "## Review Queue",
    "",
    "| # | Song | Status | YouTube text | Anchor rate | Common rate | YouTube title |",
    "|---:|---|---|---|---:|---:|---|",
    ...reviewRows.map(
      (result) =>
        `| ${result.number.replace("HYMN-", "")} | ${result.title.replace(/\|/g, "/")} | ${result.status} | ${result.youtubeTextSource} (${result.youtubeTextChars}) | ${result.anchorRate} | ${result.commonRate} | ${result.youtubeTitle.replace(/\|/g, "/")} |`
    ),
    "",
    "## Output",
    "",
    `- ${OUTPUT_CSV_PATH}`,
    "",
  ].join("\n");
  fs.writeFileSync(OUTPUT_REPORT_PATH, report);

  console.log(
    JSON.stringify(
      {
        checked: results.length,
        counts: Object.fromEntries(statusRows),
        csv: OUTPUT_CSV_PATH,
        report: OUTPUT_REPORT_PATH,
      },
      null,
      2
    )
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
